name: Chanllenge One
on: push
jobs:
    job1:
        name: JobUbuntu
        runs-on: ubuntu-latest
        steps:
            - name: Show Date
              run: date
    job2:
        name: JobWindows
        runs-on: windows-latest
        steps:
            - name: Show Date
              run: Get-Date
    job3:
        name: JobMacOS
        runs-on: macos-latest
        steps:
            - name: Show Date
              run: date
    job4:
        name: Job Final
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: Final Step
              run: echo "Final Job"

